server_connect_timeout: 5000
listeners:
  - query_port: 25577
    motd: '&1DR1TRA Network &e>> Join Now!'
    tab_list: GLOBAL_PING
    query_enabled: false
    proxy_protocol: false
    forced_hosts:
      pvp.dr1tra.net: pvp
    bind_local_address: true
    host: 0.0.0.0:25565
    max_players: 100
    tab_size: 60
    force_default_server: true
    ping_passthrough: false
    priorities:
    - lobby
servers:
  lobby:
    motd: 'DR1 Lobby 🌀'
    address: your-lobby-ip:25565
    restricted: false
  pvp:
    motd: 'PvP Server 🔥'
    address: your-pvp-ip:25565
    restricted: false
  lifesteal:
    motd: 'Lifesteal 💀'
    address: your-lifesteal-ip:25565
    restricted: false
ip_forward: true
network_compression_threshold: 256
online_mode: false
log_pings: true
